CREATE TABLE palavras (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Palavra TEXT NOT NULL CHECK(length(Palavra) <= 15),
    Idioma TEXT CHECK(Idioma IN ('Ingles', 'Portugues', 'Espanhol')),
    Categoria TEXT CHECK(length(Categoria) <= 20)
);

INSERT INTO palavras (Palavra, Idioma, Categoria) VALUES
('banana', 'Portugues', 'Comidas'),
('maca', 'Portugues', 'Comidas'),
('laranja', 'Portugues', 'Comidas'),
('abacaxi', 'Portugues', 'Comidas'),
('morango', 'Portugues', 'Comidas'),
('uva', 'Portugues', 'Comidas'),
('melancia', 'Portugues', 'Comidas'),
('pera', 'Portugues', 'Comidas'),
('kiwi', 'Portugues', 'Comidas'),
('abacate', 'Portugues', 'Comidas'),
('manga', 'Portugues', 'Comidas'),
('pessego', 'Portugues', 'Comidas'),
('limao', 'Portugues', 'Comidas'),
('goiaba', 'Portugues', 'Comidas'),
('caju', 'Portugues', 'Comidas'),
('ameixa', 'Portugues', 'Comidas'),
('figo', 'Portugues', 'Comidas'),
('pitaya', 'Portugues', 'Comidas'),
('carambola', 'Portugues', 'Comidas'),
('framboesa', 'Portugues', 'Comidas');

INSERT INTO palavras (Palavra, Idioma, Categoria) VALUES
('medico', 'Portugues', 'Profissoes'),
('engenheiro', 'Portugues', 'Profissoes'),
('professor', 'Portugues', 'Profissoes'),
('padeiro', 'Portugues', 'Profissoes'),
('policial', 'Portugues', 'Profissoes'),
('advogado', 'Portugues', 'Profissoes'),
('jornalista', 'Portugues', 'Profissoes'),
('veterinario', 'Portugues', 'Profissoes'),
('cantor', 'Portugues', 'Profissoes'),
('cozinheiro', 'Portugues', 'Profissoes'),
('fazendeiro', 'Portugues', 'Profissoes'),
('piloto', 'Portugues', 'Profissoes'),
('arquiteto', 'Portugues', 'Profissoes'),
('pedreiro', 'Portugues', 'Profissoes'),
('eletricista', 'Portugues', 'Profissoes'),
('garcom', 'Portugues', 'Profissoes'),
('marceneiro', 'Portugues', 'Profissoes'),
('ferreiro', 'Portugues', 'Profissoes'),
('carteiro', 'Portugues', 'Profissoes'),
('psicologo', 'Portugues', 'Profissoes');

-- Categoria: Animais
INSERT INTO palavras (Palavra, Idioma, Categoria) VALUES
('cachorro', 'Portugues', 'Animais'),
('gato', 'Portugues', 'Animais'),
('elefante', 'Portugues', 'Animais'),
('papagaio', 'Portugues', 'Animais'),
('tigre', 'Portugues', 'Animais'),
('leao', 'Portugues', 'Animais'),
('pato', 'Portugues', 'Animais'),
('coelho', 'Portugues', 'Animais'),
('macaco', 'Portugues', 'Animais'),
('vaca', 'Portugues', 'Animais'),
('cavalo', 'Portugues', 'Animais'),
('ovelha', 'Portugues', 'Animais'),
('zebra', 'Portugues', 'Animais'),
('girafa', 'Portugues', 'Animais'),
('cobra', 'Portugues', 'Animais'),
('sapo', 'Portugues', 'Animais'),
('formiga', 'Portugues', 'Animais'),
('borboleta', 'Portugues', 'Animais'),
('abelha', 'Portugues', 'Animais'),
('aranha', 'Portugues', 'Animais');

-- Categoria: Esportes
INSERT INTO palavras (Palavra, Idioma, Categoria) VALUES
('futebol', 'Portugues', 'Esportes'),
('volei', 'Portugues', 'Esportes'),
('tenis', 'Portugues', 'Esportes'),
('natacao', 'Portugues', 'Esportes'),
('basquete', 'Portugues', 'Esportes'),
('handebol', 'Portugues', 'Esportes'),
('ginastica', 'Portugues', 'Esportes'),
('boxe', 'Portugues', 'Esportes'),
('atletismo', 'Portugues', 'Esportes'),
('judo', 'Portugues', 'Esportes'),
('ciclismo', 'Portugues', 'Esportes'),
('hipismo', 'Portugues', 'Esportes'),
('surfe', 'Portugues', 'Esportes'),
('skate', 'Portugues', 'Esportes'),
('rugby', 'Portugues', 'Esportes'),
('golfe', 'Portugues', 'Esportes'),
('automobilismo', 'Portugues', 'Esportes'),
('patinacao', 'Portugues', 'Esportes'),
('esgrima', 'Portugues', 'Esportes'),
('wrestling', 'Portugues', 'Esportes');

-- Categoria: Transportes
INSERT INTO palavras (Palavra, Idioma, Categoria) VALUES
('carro', 'Portugues', 'Transportes'),
('moto', 'Portugues', 'Transportes'),
('bicicleta', 'Portugues', 'Transportes'),
('onibus', 'Portugues', 'Transportes'),
('trem', 'Portugues', 'Transportes'),
('aviacao', 'Portugues', 'Transportes'),
('navio', 'Portugues', 'Transportes'),
('caminhao', 'Portugues', 'Transportes'),
('barco', 'Portugues', 'Transportes'),
('cavalo', 'Portugues', 'Transportes'),
('skate', 'Portugues', 'Transportes'),
('trator', 'Portugues', 'Transportes'),
('helicoptero', 'Portugues', 'Transportes'),
('jet ski', 'Portugues', 'Transportes'),
('taxi', 'Portugues', 'Transportes'),
('metro', 'Portugues', 'Transportes'),
('van', 'Portugues', 'Transportes'),
('aviao', 'Portugues', 'Transportes'),
('ferryboat', 'Portugues', 'Transportes'),
('limusine', 'Portugues', 'Transportes');
